### PR TITLE
WIP: Added Navio Original Support

### PR DESCRIPTION
**Pull request by yconst**
Adds support for the NAVIO (original) HAT.

Thanks to @adricl , previous mr was https://github.com/yconst/burro/pull/30

### CODE REVIEW

**Comment by adricl** [comment]
Ok it tested this with the f710 and now the throttle does not work. I have not tested this with the tensor flow modules.

**Comment by yconst** [comment]
I've removed the right stick throttle functionality because it made steering difficult sometimes. Have you tried with the left cross pad? Hitting forward (and optionally pressing on the left front soft button) should do the trick. Also take a look here https://github.com/yconst/burro/wiki/Control-a-Burro-car-using-the-F710-Gamepad , T and F is what I'm referring to.

**Comment by adricl** [comment]
Ok cool that works. Did you want me to test anything else?

**Comment by yconst** [comment]
I think everything works ok. Merging. 

Thanks a lot for the contribution.

**Pull request merged**
