### PR TITLE
Added Navio Original Support

### PR DESCRIPTION
**Pull request by adricl**
Added Navio original support for burro. I have tested this with an F710 controller. I am cant get the RCInput to work because it seems Navio has stopped supporting the Python RCInput libraries. 

Please note I have changed the Navio from the original to Navio2 to reflect the correct name.

### CODE REVIEW

**Comment by yconst** [comment]
That's great, thanks! I'll check it out tonight or tomorrow to make sure that it works fine for the other controllers as well.

**Comment by adricl** [comment]
OK cool, I also as I don't have the Navio2 could you please check if the board detection works correctly. Also if you want to me to change anything please don't hesitate to ask. Great work with this framework!

**Comment by yconst** [comment]
Ok will do. I'll probably delay this a few days tho, cause I got some stuff I need to get done till next weekend. I'll take a look right after.

Thanks again for the contribution!

**Comment by yconst** [comment]
I've checked this and seems to be working. I made some changes and opened a new mr here: https://github.com/yconst/burro/pull/31

Can you please check if the NAVIO support works for that mr?

Also, does this add support for the NAVIO or the NAVIO+ hat?

**Comment by adricl** [comment]
I will check the code today. It supports Navio+ hat.

**Pull request closed without merging**
